fix: dkms package builds

diff --git a/master b/master
--- a/master
+++ b/master
@@ -42,6 +42,12 @@ if ! which dh_make > /dev/null ; then
   echo "  sudo apt install dh-make"
   exit 1
 fi
+# check for dh_dkms
+if ! which dh_dkms > /dev/null ; then
+  echo "ERROR: dh_dkms was not found. Please install it first by running:"
+  echo "  sudo apt install dh-dkms"
+  exit 1
+fi
 # check for Python module packaging used in configureRelease for version comparison
 if ! python3 -m packaging.version > /dev/null ; then
   echo "ERROR: python package 'packaging' not found."
