feat: auto-install script prerequisites if missing

diff --git a/master b/master
--- a/master
+++ b/master
@@ -36,36 +36,44 @@ function showHelp() {
 }
 
 ## check prerequisites ##
+PREREQS_OK=1
 if ! which pbuilder > /dev/null ; then
   echo "ERROR: pbuilder was not found. Please install it first by running:"
-  echo "  sudo apt install pbuilder"
-  exit 1
+  PREREQS_OK=0
 fi
 # check for dh_make
 if ! which dh_make > /dev/null ; then
   echo "ERROR: dh_make was not found. Please install it first by running:"
-  echo "  sudo apt install dh-make"
-  exit 1
+  PREREQS_OK=0
 fi
 # check for dh_dkms
 if ! which dh_dkms > /dev/null ; then
   echo "ERROR: dh_dkms was not found. Please install it first by running:"
-  echo "  sudo apt install dh-dkms"
-  exit 1
+  PREREQS_OK=0
 fi
 # check for dh_python3
 if ! which dh_python3 > /dev/null ; then
   echo "ERROR: dh_python3 was not found. Please install it first by running:"
-  echo "  sudo apt install dh-python"
-  exit 1
+  PREREQS_OK=0
 fi
 # check for Python module packaging used in configureRelease for version comparison
 if ! python3 -m packaging.version > /dev/null ; then
   echo "ERROR: python package 'packaging' not found."
-  echo "  sudo apt install python3-packaging"
-  echo "  or using pip3:"
-  echo "  pip3 install packaging"
-  exit 1
+  PREREQS_OK=0
+fi
+
+if [ "$PREREQS_OK" != "1" ]; then
+  echo "Need to install the following prerequisitions:"
+  echo apt-get install pbuilder dh-make dh-dkms dh-python python3-packaging
+  apt-get install -s pbuilder dh-make dh-dkms dh-python python3-packaging
+  echo ""
+  read -n1 -p "Proceed installing these packages (y/n)? " ANSWER
+  echo ""
+  if [ "$ANSWER" != "y" -a "$ANSWER" != "Y" ]; then
+    echo "Cannot proceed without prerequisitions."
+    exit 1
+  fi
+  sudo apt-get install pbuilder dh-make dh-dkms dh-python python3-packaging
 fi
 
 use_preseed_repository=0
